name: Accessibility Check

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    paths:
      - 'data.json'
      - 'scripts/check_accessibility.py'

jobs:
  accessibility-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run accessibility check
      run: |
        python scripts/check_accessibility.py data.json --check-all
        
    - name: Commit and push changes
      if: github.event_name != 'pull_request'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update accessibility status [skip ci]"
          git push
        fi
