name: Ingest from Google Forms (to PR)

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch CSV
        run: |
          if [ -z "${{ secrets.SHEET_CSV_URL }}" ]; then
            echo "SHEET_CSV_URL secret is not set"; exit 1
          fi
          curl -L "$SHEET_CSV_URL" -o submissions.csv
        env:
          SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}

      - name: Install Python (for parser)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Inspect CSV (debug)
        run: |
          wc -l submissions.csv || true
          echo "----- HEAD -----"
          head -5 submissions.csv || true

      - name: Parse and update data.json
        id: ingest
        run: |
          python scripts/ingest_google_forms.py submissions.csv data.json out.json
          if cmp -s data.json out.json; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
          else
            mv out.json data.json
            echo "no_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: steps.ingest.outputs.no_changes == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(forms): ingest new resources from Google Forms"
          title: "chore(forms): add resources from Google Forms"
          body: "This PR adds new resources from the public submission form."
          branch: "chore/forms-ingest"
          delete-branch: true
