name: Ingest Google Forms Data

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    paths:
      - 'scripts/ingest_google_forms.py'
      - 'data.json'

# Note: This workflow fetches data directly from Google Sheets using CSV export URL.
# 
# Required GitHub Secrets:
# - SHEET_CSV_URL: The CSV export URL from your Google Sheet
# 
# To set up:
# 1. Go to your Google Sheet
# 2. Click File → Download → Comma-separated values (.csv)
# 3. Copy the download URL from your browser's network tab, or use:
#    https://docs.google.com/spreadsheets/d/YOUR_SHEET_ID/export?format=csv&gid=0
# 4. Add the URL as a GitHub secret named SHEET_CSV_URL

jobs:
  ingest-forms:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Fetch CSV from Google Sheets
      run: |
        if [ -z "${{ secrets.SHEET_CSV_URL }}" ]; then
          echo "SHEET_CSV_URL secret is not set"; exit 1
        fi
        curl -L "$SHEET_CSV_URL" -o submissions.csv
      env:
        SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Google Forms ingestion
      run: |
        python scripts/ingest_google_forms.py data.json data.json submissions.csv
        
    - name: Commit and push changes
      if: github.event_name != 'pull_request'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update data from Google Forms submissions [skip ci]"
          git push
        fi
