name: Ingest Google Forms Data

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    paths:
      - 'scripts/ingest_google_forms.py'
      - 'data.json'

# Note: This workflow fetches data directly from public Google Sheets.
# 
# Required GitHub Secrets:
# - GOOGLE_SHEETS_ID: The ID of your Google Sheet (from the URL)
# 
# To set up:
# 1. Make sure your Google Sheet is public (Anyone with the link can view)
# 2. Add the Google Sheets ID as a GitHub secret

jobs:
  ingest-forms:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Google Forms ingestion
      env:
        GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
      run: |
        python scripts/ingest_google_forms.py data.json data.json
        
    - name: Commit and push changes
      if: github.event_name != 'pull_request'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update data from Google Forms submissions [skip ci]"
          git push
        fi
